# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - dev-canned-responses-fe

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: npm install, build, and test
        run: |
          yarn
          npm run build --if-present

      - name: Zip node_modules for deployment
        run: |
          zip -q ./node_modules.zip ./node_modules -r

      - name: Zip artifact for deployment
        run: |
          cd dist
          zip ../release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: release.zip

      - name: Upload artifact (node_modules) for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-modules
          path: node_modules.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: Download artifact node-modules from build job
        uses: actions/download-artifact@v3
        with:
          name: node-modules

      - name: Unzip artifact for deployment
        run: |
          unzip release.zip
          unzip -q node_modules.zip
          rm release.zip node_modules.zip
          tree
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_F2B3A56A9EE544D98409CEEDB92DDAB4 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_AD9D69A610BD4113AC5A98EC5AFC6C6F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_FE79D7FBF73C4992842B8BDC07CC9271 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'dev-canned-responses-fe'
          slot-name: 'Production'
          package: .
          
